import Footer from "@/components/Footer";
import NavBar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" min-h-screen bg-green-500  overflow-hidden">
        <NavBar />
          {children}
          <SpeedInsights />
          <Toaster richColors position="top-left"/>
        {/* <Footer/> */}
      </body>
    </html>
  );
}
